src/main/java/edu/university/entity/Application.java
package edu.university.entity;

import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.nio.file.Path;
import java.util.Date;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * Represents users application for educational programme
 */
public class Application implements Serializable {
    private int id;
    private int userId;
    @NotNull(message = "Scores must contain at least one subject")
    @Size(min = 1,message = "Scores must contain at least one subject")
    Map<Subject,Score> scores;
    private int programmeId;

    Application (Builder builder){
        this.id = builder.id;
        this.userId = builder.userId;
        this.programmeId = builder.programmeId;
        this.scores = builder.scores;
    }

    public int getId() {
        return id;
    }

    public int getUserId() {
        return userId;
    }

    public int getProgrammeId() {
        return programmeId;
    }

    public Map<Subject, Score> getScores() {
        return scores;
    }

    @Override
    public String toString() {
        return "Application{" +
                "id=" + id +
                ", userId=" + userId +
                ", programmeId=" + programmeId +
                ", scores=" + scores +
                '}';
    }

    public static class Builder{
        Map<Subject,Score> scores;
        private int id;
        private int userId;
        private int programmeId;

        public Builder id(int id){
            this.id = id;
            return this;
        }

        public Builder userId(int userId){
            this.userId = userId;
            return this;
        }

        public Builder programmeId(int programmeId){
            this.programmeId = programmeId;
            return this;
        }

        public Builder scores(Map<Subject,Score> scores){
            this.scores = scores;
            return this;
        }

        public Application build(){
            return new Application(this);
        }
    }
}

src/main/java/edu/university/entity/Department.java
package edu.university.entity;

import edu.university.entity.validator.MaxLength;
import edu.university.entity.validator.NotNullNotEmpty;
import edu.university.entity.validator.RegexMatch;

import java.io.Serializable;
import java.util.Objects;

import static edu.university.entity.validator.RegexMatch.PATTERN_NAME;
import static edu.university.entity.validator.RegexMatch.PATTERN_TEXT;

/**
 * Represents department, contains basic information like about name, description. Departments can be nested,
 * parentId is an id of container for current department
 */
public class Department implements Serializable {
    private final int id;
    private final int parentId;

    @NotNullNotEmpty(message = "Department name can't be empty")
    @RegexMatch(pattern = PATTERN_TEXT,message = "Forbidden symbol(s) is used for department name")
    @MaxLength(length=150,message = "Department name must be less then 150 characters long")
    private final String name;

    @NotNullNotEmpty(message = "Department name can't be empty")
    @RegexMatch(pattern = PATTERN_TEXT,message = "Forbidden symbol(s) is used for department description")
    @MaxLength(length=255,message = "Description must be less then 255 characters long")
    private final String description;

    public Department(Builder builder) {
        this.id = builder.id;
        this.parentId = builder.parentId;
        this.name = builder.name;
        this.description = builder.description;
    }

    public int getId() {
        return id;
    }

    public int getParentId() {
        return parentId;
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Department that = (Department) o;
        return id == that.id;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public String toString() {
        return "Department{" +
                "id=" + id +
                ", parentId=" + parentId +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                '}';
    }

    public static class Builder{
        private int id;
        private int parentId;
        private String name;
        private String description;

        public Builder id(int id) {
            this.id = id;
            return this;
        }

        public Builder parentId(int parentId) {
            this.parentId = parentId;
            return this;
        }

        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public Builder description(String description){
            this.description = description;
            return this;
        }

        public Department build(){
            return new Department(this);
        }

    }
}

src/main/java/edu/university/entity/Programme.java
package edu.university.entity;

import edu.university.entity.validator.MaxLength;
import edu.university.entity.validator.NotNullNotEmpty;
import edu.university.entity.validator.RegexMatch;

import java.io.Serializable;
import java.util.Objects;

import static edu.university.entity.validator.RegexMatch.PATTERN_NAME;
import static edu.university.entity.validator.RegexMatch.PATTERN_TEXT;

/**
 * Represents educational programme
 */
public class Programme implements Serializable {
   private final int id;
   private final int departmentId;

   @NotNullNotEmpty(message = "Programme name can't be empty")
   @RegexMatch(pattern = PATTERN_TEXT,message = "Forbidden symbol(s) is used for programme name")
   @MaxLength(length=150,message = "Programme name be less then 150 characters long")
   private final String name;

   @NotNullNotEmpty(message = "Programme name can't be empty")
   @RegexMatch(pattern = PATTERN_TEXT,message = "Forbidden symbol(s) is used for programme short description")
   @MaxLength(length=255,message = "Short description must be less then 255 characters long")
   private final String shortDescription;

   public Programme(Builder builder) {
      this.id = builder.id;
      this.departmentId = builder.departmentId;
      this.name = builder.name;
      this.shortDescription = builder.shortDescription;
   }

   @Override
   public boolean equals(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;
      Programme programme = (Programme) o;
      return id == programme.id;
   }

   @Override
   public int hashCode() {
      return Objects.hash(id);
   }

   @Override
   public String toString() {
      return "Programme{" +
              "id=" + id +
              ", departmentId=" + departmentId +
              ", name='" + name + '\'' +
              ", shortDescription='" + shortDescription + '\'' +
              '}';
   }

   public int getId() {
      return id;
   }

   public int getDepartmentId() {
      return departmentId;
   }

   public String getName() {
      return name;
   }

   public String getShortDescription() {
      return shortDescription;
   }

   public static class Builder{
      private int id;
      private int departmentId;
      private String name;
      private String shortDescription;

      public Builder id(int id) {
         this.id = id;
         return this;
      }

      public Builder departmentId(int departmentId) {
         this.departmentId = departmentId;
         return this;
      }

      public Builder name(String name) {
         this.name = name;
         return this;
      }

      public Builder shortDescription(String shortDescription) {
         this.shortDescription = shortDescription;
         return this;
      }


      public Programme build(){
         return new Programme(this);
      }
   }

}

src/main/java/edu/university/entity/Report.java
package edu.university.entity;

import java.util.List;
import java.util.Map;

/**
 * Represents final report for educational programme
 */
public class Report {
    private Programme programme;
    private ProgrammeDetails programmeDetails;
    private List<Map<String,String>> reportRows;

    public Report(Builder builder) {
        this.programme = builder.programme;
        this.programmeDetails = builder.programmeDetails;
        this.reportRows = builder.reportRows;
    }

    public Programme getProgramme() {
        return programme;
    }

    public ProgrammeDetails getProgrammeDetails() {
        return programmeDetails;
    }

    public List<Map<String, String>> getReportRows() {
        return reportRows;
    }

    public static class Builder {
        private Programme programme;
        private ProgrammeDetails programmeDetails;
        private List<Map<String,String>> reportRows;

        public Builder programme(Programme programme) {
            this.programme = programme;
            return this;
        }

        public Builder programmeDetails(ProgrammeDetails programmeDetails) {
            this.programmeDetails = programmeDetails;
            return this;
        }

        public Builder reportRows(List<Map<String,String>> reportRows){
            this.reportRows = reportRows;
            return this;
        }

        public Report build(){
            return new Report(this);
        }
    }

}

src/main/java/edu/university/entity/dto/Paginator.java
package edu.university.entity.dto;

/**
 * Used for separating results into discrete pages
 */
public class Paginator {
    private int totalEntries;
    private int currentPage = 1;
    private int pageSize = 10;

    public int getTotalEntries() {
        return totalEntries;
    }

    public void setTotalEntries(int totalEntries) {
        this.totalEntries = totalEntries;
    }

    public int getTotalPages() {
        if (pageSize != 0) {
            return (int) Math.ceil((double) totalEntries / pageSize);
        }
        return 0;
    }

    public int getCurrentPage() {
        return currentPage;
    }

    public void setCurrentPage(int currentPage) {
        this.currentPage = currentPage;
    }

    public int getPageSize() {
        return pageSize;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

}

src/main/webapp/WEB-INF/jsp/apply.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
<c:set var="pageTitle" value="Apply for programme" scope="page"/>
<%@ include file="./common/header.jspf" %>

<body>

<%@ include file="./common/navbar.jspf" %>
<%@ include file="./common/sidenav.jspf" %>

<div class="row">
    <div class="col s3"></div>
    <div class="col s6">
        <div class="col s12 m12">
            <h3 class="header center-align">Apply for programme</h3>
            <div class="card horizontal">
                <div class="card-stacked">
                    <div class="card-content">
                        <div class="row">
                            <c:if test="${not empty sessionScope.errorMessage}">
                                <div class="row red accent-1">
                                    <h6 class="center-align">${errorMessage}</h6>
                                </div>
                                <c:remove var="errorMessage" scope="session" />
                            </c:if>

                            <h5>${programme.name}</h5>
                            <p>${programme.shortDescription}</p>
                            <br>
                            <p>
                                Budget places: ${programmeDetails.budgetPlaces}; Total places: ${programmeDetails.totalPlaces}
                            </p>
                        </div>

                        <div class="row">
                            <h6 class="center-align red-text text-darken-1">${applyError}</h6>
                            <c:remove var="applyError" scope="session"/>

                            <form class="col s12" action="${appName}/app" method="post">
                                <div class="row">
                                    <div class="input-field col s6">
                                        <input id="firstName" value="${loggedUser.firstName}" type="text" disabled>
                                        <label for="firstName">First Name</label>
                                    </div>
                                    <div class="input-field col s6">
                                        <input id="lastName" value="${loggedUser.lastName}" type="text" disabled>
                                        <label for="firstName">Last Name</label>
                                    </div>
                                </div>

                                <div class="row">

                                    <h5>Requirements:</h5>

                                    <c:forEach var="group" items="${programmeRequirements}" varStatus="loop">
                                        <div class="input-field col s6">
                                            <select name="group_subject_${loop.index}" class="validate" required aria-required="true">
                                                <option value="">Select subject</option>
                                                <c:forEach var="subject" items="${group.subjects}">
                                                    <option value="${subject.id}">${subject.name}</option>
                                                </c:forEach>
                                            </select>
                                            <label><ex:subjectIndex index="${loop.index}"/></label>
                                            <span class="helper-text" data-error="Please, choose subject" data-success="ok"></span>
                                        </div>

                                        <div class="input-field col s4">
                                            <input id="score${loop.index}" name="group_score_${loop.index}" value="" type="number" class="validate" min="${group.minScore}" max="200" required aria-required="true">
                                            <label for="score${loop.index}">Score (min: ${group.minScore})</label>
                                            <span class="helper-text" data-error="Please, enter your score" data-success="ok"></span>
                                        </div>
                                    </c:forEach>
                                </div>

                                <div class="row">
                                    <div class="center-align">
                                        <input name="programmeId" value="${programme.id}" type="hidden">
                                        <button class="btn waves-effect waves-light" type="submit"  name="cmd" value="apply">
                                            Submit
                                        </button>
                                    </div>

                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col s3"></div>
</div>

<%@ include file="./common/footer.jspf" %>
<script type="text/javascript" src="${appName}/static/js/select.js"></script>

</body>
</html>

src/main/webapp/WEB-INF/jsp/delete_programme.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="ex" uri="customTags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
<c:set var="pageTitle" value="Delete programme" scope="page"/>
<%@ include file="./common/header.jspf" %>

<body>
<%@ include file="./common/navbar.jspf" %>
<%@ include file="./common/sidenav.jspf" %>

<div class="container">
    <h3 class="header center-align">
        Delete programme
    </h3>

    <div class="row">

        <div class="col s2">

        </div>

        <div class="col s8">
            <div class="row">
                <div class="card horizontal">
                    <div class="card-stacked">
                        <div class="card-content">

                            <form class="col s12" action="${appName}/app" method="post">

                                <div class="row">
                                    <div class="row center-align">
                                        <p>Warning! If you press delete button you will delete programme and all applications forever. Recovery is not possible</p>
                                    </div>
                                    <div class="switch">
                                        <label>
                                            <input type="checkbox" id="confirmCheckBox" onchange="confirm()">
                                            <span class="lever"></span>
                                            I understand, continue anyway
                                        </label>
                                    </div>
                                    <input type="hidden" name="confirmationKey" value="${confirmationKey}">
                                    <input type="hidden" name="programmeId" value="${programmeId}">
                                    <c:remove var="programmeId" scope="session"/>
                                    <br>
                                    <div class="row center-align">
                                        <button class="btn waves-effect waves-light red" disabled type="submit" id="confirmButton"  name="cmd" value="deleteProgramme">
                                            DELETE
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>

        </div>

        <div class="col s2">

        </div>

    </div>

</div>


<jsp:include page="./common/footer.jspf"/>
<script type="text/javascript" src="${appName}/static/js/select.js"></script>
<script type="text/javascript" src="${appName}/static/js/confirm.js"></script>

</body>
</html>

src/main/webapp/WEB-INF/jsp/departments.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="ex" uri="customTags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
<c:set var="pageTitle" value="Welcome page" scope="page"/>
<%@ include file="./common/header.jspf" %>

<body>
<%@ include file="./common/navbar.jspf" %>
<%@ include file="./common/sidenav.jspf" %>

<div class="container">
    <c:if test="${empty parentDepartment}">
        <h3 class="header center-align">Specialities and educational programs</h3>
    </c:if>
    <c:if test="${not empty parentDepartment}">
        <a href="${appName}/app?cmd=departments&parentId=${parentDepartment.parentId}">
            <h3 class="header">
                <i class="material-icons">navigate_before</i>
                    ${parentDepartment.name}
            </h3>
        </a>
    </c:if>


    <div class="row">

        <c:forEach var="department" items="${departments}">
            <div class='col s12 m4'>
                <ex:card title="${department.name}"
                         href="${appName}/app?cmd=departments&parentId=${department.getId()}"
                         style="teal lighten-5">
                    <p>${department.description}</p>
                </ex:card>
            </div>
        </c:forEach>

    </div>

    <div class="row">
        <c:forEach var="programme" items="${programmes}">
            <div class='col s12 m4'>
                <ex:card title="${programme.name}"
                         href="${appName}/app?cmd=programme&programmeId=${programme.id}"
                         style="green lighten-4">
                    <p>${programme.shortDescription}</p>
                </ex:card>
            </div>
        </c:forEach>
    </div>


</div>


<jsp:include page="./common/footer.jspf"/>

</body>
</html>

src/main/webapp/WEB-INF/jsp/manage_users.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="ex" uri="customTags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
<c:set var="pageTitle" value="Manage users" scope="page"/>
<%@ include file="./common/header.jspf" %>

<body>
<%@ include file="./common/navbar.jspf" %>
<%@ include file="./common/sidenav.jspf" %>

<div class="container">

    <h3 class="header">
        Manage users
    </h3>


    <div class="row">
        <div class="row">
            <form>
                <div class="input-field col s4">
                    <i class="prefix"><img src="https://img.icons8.com/ios/32/000000/filter-and-sort.png"/></i>
                    <input name="firstName" value="${firstName}" type="text" id="autocomplete-firstName" class="autocomplete">
                    <label for="autocomplete-firstName">Filter by first name</label>
                </div>
                <div class="input-field col s4">
                    <i class="prefix"><img src="https://img.icons8.com/ios/32/000000/filter-and-sort.png"/></i>
                    <input name="lastName" value="${lastName}" type="text" id="autocomplete-lastName" class="autocomplete">
                    <label for="autocomplete-lastName">Filter by last name</label>
                </div>
                <div class="input-field col s3">
                    <i class="prefix"><img src="https://img.icons8.com/ios/32/000000/filter-and-sort.png"/></i>
                    <input name="email" value="${email}" type="text" id="autocomplete-email" class="autocomplete">
                    <label for="autocomplete-email">Filter by email</label>
                </div>


                <div class="input-field col s1">
                    <button class="btn waves-effect waves-light" type="submit" name="cmd" value="manageUsers">
                        Search
                    </button>
                </div>
            </form>

        </div>
        <table class="highlight">
            <thead>
            <tr>
                <th class="left-align">First name</th>
                <th class="left-align">Last name</th>
                <th class="left-align">Email</th>
                <th class="left-align">Role</th>
            </tr>
            </thead>
            <tbody>
            <c:if test="${empty users}">
                <p class="center-align">Nothing found</p>
            </c:if>
            <c:if test="${not empty users}">

                <c:forEach var="entry" items="${users}">

                    <tr style="cursor: pointer;"
                        onclick="window.location='${appName}/app?cmd=manageOneUser&userId=${entry.id}'">
                        <td class="left-align">${entry.firstName}</td>
                        <td class="left-align">${entry.lastName}</td>
                        <td class="left-align">${entry.email}</td>
                        <td class="left-align">${entry.role}</td>
                    </tr>

                </c:forEach>
            </c:if>
            </tbody>
        </table>


<%--        <c:if test="${not empty searchResult}">--%>
<%--            <ex:pagination currentPage="${searchResult.currentPage}"--%>
<%--                           lastPage="${searchResult.totalPages}"--%>
<%--                           url="${SELF}"/>--%>
<%--        </c:if>--%>
    </div>

</div>


<jsp:include page="./common/footer.jspf"/>
<script type="text/javascript" src="${appName}/static/js/select.js"></script>

</body>
</html>

src/main/webapp/WEB-INF/jsp/reports.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="ex" uri="customTags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
<c:set var="pageTitle" value="Reports" scope="page"/>
<%@ include file="./common/header.jspf" %>

<body>
<%@ include file="./common/navbar.jspf" %>
<%@ include file="./common/sidenav.jspf" %>

<div class="container">

    <h3 class="header">
        Manage reports
    </h3>


    <div class="row">
        <table class="highlight">
            <thead>
            <tr>
                <th class="left-align">Programme</th>
                <th class="left-align">Report</th>
                <th class="left-align">Link</th>
            </tr>
            </thead>
            <tbody>
            <c:if test="${empty reports}">
                <tr><td><p class="center-align">Nothing found</p></td></tr>
            </c:if>
            <c:if test="${not empty reports}">

                <c:forEach var="entry" items="${reports}">

                    <tr>
                        <td class="left-align">${entry.getKey().name}</td>
                        <td class="left-align">${entry.getValue().name}</td>
                        <td class="left-align"><a href="${appName}/app?cmd=getReport&reportId=${entry.getValue().id}">download</a></td>
                    </tr>

                </c:forEach>
            </c:if>
            </tbody>
        </table>


        <%--        <c:if test="${not empty searchResult}">--%>
        <%--            <ex:pagination currentPage="${searchResult.currentPage}"--%>
        <%--                           lastPage="${searchResult.totalPages}"--%>
        <%--                           url="${SELF}"/>--%>
        <%--        </c:if>--%>
    </div>

</div>


<jsp:include page="./common/footer.jspf"/>
<script type="text/javascript" src="${appName}/static/js/select.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.autocomplete');
        var instances = M.Autocomplete.init(elems, {
            minLength:1,
            data: {
                <c:forEach var="programme" items="${allProgrammes}">
    "${programme.name}":null,
</c:forEach>
            }
        });
    });


</script>

</body>
</html>

src/main/webapp/WEB-INF/jsp/search.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="ex" uri="customTags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
<c:set var="pageTitle" value="Programme information" scope="page"/>
<%@ include file="./common/header.jspf" %>

<body>
<%@ include file="./common/navbar.jspf" %>
<%@ include file="./common/sidenav.jspf" %>

<div class="container">

    <h3 class="header">
        Search programme
    </h3>


    <div class="row">
        <div class="row">
            <form>
                <div class="input-field col s6">
                    <i class="prefix"><img src="https://img.icons8.com/ios/32/000000/filter-and-sort.png"/></i>
                    <input name="programme" value="${programmeName}" type="text" id="autocomplete-input" class="autocomplete">
                    <label for="autocomplete-input">Programme name</label>
                </div>
                <div class="input-field col s2">
                    <select name="dates">
                        <option value="all" ${dateQuery=="all"?"selected":""}>All programmes</option>
                        <option value="opened" ${dateQuery=="opened"?"selected":""}>Opened now</option>
                        <option value="future" ${dateQuery=="future"?"selected":""}>Future</option>
                        <option value="past" ${dateQuery=="past"?"selected":""}>Past</option>
                    </select>
                    <label>Filter dates</label>
                </div>
                <div class="input-field col s2">
                    <select name="sort">
                        <optgroup label="By name">
                            <option value="byNameAz" ${sortingType=="byNameAz"?"selected":""}>A-z</option>
                            <option value="byNameZa" ${sortingType=="byNameZa"?"selected":""}>z-A</option>
                        </optgroup>
                        <optgroup label="By budget places">
                            <option value="byBudget19" ${sortingType=="byBudget19"?"selected":""}>1-9</option>
                            <option value="byBudget91" ${sortingType=="byBudget91"?"selected":""}>9-1</option>
                        </optgroup>
                        <optgroup label="By total places">
                            <option value="byTotal19" ${sortingType=="byTotal19"?"selected":""}>1-9</option>
                            <option value="byTotal91" ${sortingType=="byTotal91"?"selected":""}>9-1</option>
                        </optgroup>
                    </select>
                    <label>Sorting</label>
                </div>
                <div class="input-field col s1">
                    <select name="pageSize">
                        <option value="10" ${pageSize=="10"?"selected":""}>10</option>
                        <option value="20" ${pageSize=="20"?"selected":""}>20</option>
                        <option value="50" ${pageSize=="50"?"selected":""}>50</option>
                    </select>
                    <label>Qty on page</label>
                </div>
                <div class="input-field col s1">
                    <button class="btn waves-effect waves-light" type="submit" name="cmd" value="searchProgramme">
                        Search
                    </button>
                </div>
            </form>

        </div>
        <table class="highlight">
            <thead>
            <tr>
                <th>Programme name</th>
                <th class="right-align">Budget places</th>
                <th class="right-align">Total places</th>
                <th class="center-align">Applications start date</th>
                <th class="center-align">Applications end date</th>
                <th></th>
            </tr>
            </thead>
            <tbody>

            <c:if test="${not empty programmes}">

                <c:forEach var="tuple" items="${programmes}">

                    <tr>

                        <td><a href="${appName}/app?cmd=programme&programmeId=${tuple.first.id}"
                               class="black-text">${tuple.first.name}</a></td>
                        <td class="right-align">${tuple.second.budgetPlaces}</td>
                        <td class="right-align">${tuple.second.totalPlaces}</td>
                        <td class="center-align">${tuple.second.admissionsStartDate}</td>
                        <td class="center-align">${tuple.second.admissionsEndDate}</td>
                        <td>
                            <a href="${appName}/app?cmd=programme&programmeId=${tuple.first.id}" class="black-text">
                                <i class="material-icons right">info_outline</i>
                            </a>
                        </td>

                    </tr>

                </c:forEach>
            </c:if>
            </tbody>
        </table>

        <c:if test="${empty programmes}">
                <p class="center-align">Nothing found</p>
        </c:if>

        <c:if test="${not empty programmes}">
            <ex:pagination currentPage="${paginator.currentPage}"
                           lastPage="${paginator.totalPages}"
                           url="${SELF}"/>
        </c:if>
    </div>

</div>


<jsp:include page="./common/footer.jspf"/>
<script type="text/javascript" src="${appName}/static/js/select.js"></script>

</body>
</html>